/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apache_poi;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Iterator;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.util.IOUtils;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class App {
    public String getGreeting() {
        return "Hello, Running Apache POI on Java...!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        IOUtils.setByteArrayMaxOverride(900000000);
        String filePath = "app//src//main//java//apache_poi//test.xlsx";

        try (FileInputStream fis = new FileInputStream(filePath)) {
            // get the excel sheet file location
            XSSFWorkbook workbook = new XSSFWorkbook(fis);
            // XSSFSheet sheet = workbook.getSheetAt(0);
            XSSFSheet sheet = workbook.getSheet("Reservations");
            // get the total row count in the excel sheet
            Iterator<Row> iterator = sheet.rowIterator();

            int cellIndex = 0;

            while (iterator.hasNext()) {
                Row row = iterator.next();
                System.out.println(cellIndex + " | " +
                        row.getCell(0) + " | " + row.getCell(1) + " | " + row.getCell(2) + " | " + row.getCell(3)
                        + " | " + row.getCell(4));
                cellIndex++;

            }

            workbook.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
